# Generated by Django 5.1 on 2024-08-27 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro_marca_carro_placa_alter_carro_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', null=True)),
                ('cpf', models.CharField(default='', max_length=11)),
                ('nome', models.CharField(default='', max_length=50)),
                ('sobrenome', models.CharField(default='', max_length=100)),
                ('nascimento', models.IntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='carro',
            name='cor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carro',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
